services:
  tg-forwarder:
    image: oddann/tg-bot-channel-to-forum:v1.2.0
    container_name: tg-forwarder
    restart: always
    volumes:
      - /volumes:/app/volumes
    environment:
      - PYTHONUNBUFFERED=1