name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [linux/amd64, linux/arm64]

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. QEMU (для эмуляции arm на amd)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Extract SHA
      - name: Extract short SHA
        id: vars
        run: echo "sha_short=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      # 6. Build & push image per arch
      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ matrix.arch }}
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/tg-bot-channel-to-forum:${{ steps.vars.outputs.sha_short }}-${{ matrix.arch }}

  manifest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Create and push manifest
      - name: Create and push manifest
        run: |
          # Текущий SHA
          SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)

          # Собираем manifest для SHA
          docker manifest create docker.io/${{ secrets.DOCKERHUB_USERNAME }}/tg-bot-channel-to-forum:sha-${SHA_SHORT} \
            --amend docker.io/${{ secrets.DOCKERHUB_USERNAME }}/tg-bot-channel-to-forum:${SHA_SHORT}-linux/amd64 \
            --amend docker.io/${{ secrets.DOCKERHUB_USERNAME }}/tg-bot-channel-to-forum:${SHA_SHORT}-linux/arm64
          docker manifest push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/tg-bot-channel-to-forum:sha-${SHA_SHORT}

          # Всегда пушим latest
          docker manifest create docker.io/${{ secrets.DOCKERHUB_USERNAME }}/tg-bot-channel-to-forum:latest \
            --amend docker.io/${{ secrets.DOCKERHUB_USERNAME }}/tg-bot-channel-to-forum:${SHA_SHORT}-linux/amd64 \
            --amend docker.io/${{ secrets.DOCKERHUB_USERNAME }}/tg-bot-channel-to-forum:${SHA_SHORT}-linux/arm64
          docker manifest push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/tg-bot-channel-to-forum:latest

          # Если это тег релиза (vX.Y.Z) — пушим его тоже
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
            docker manifest create docker.io/${{ secrets.DOCKERHUB_USERNAME }}/tg-bot-channel-to-forum:${TAG} \
              --amend docker.io/${{ secrets.DOCKERHUB_USERNAME }}/tg-bot-channel-to-forum:${SHA_SHORT}-linux/amd64 \
              --amend docker.io/${{ secrets.DOCKERHUB_USERNAME }}/tg-bot-channel-to-forum:${SHA_SHORT}-linux/arm64
            docker manifest push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/tg-bot-channel-to-forum:${TAG}
          fi
